- hosts: dev
  become: yes
  tasks:
     - name: Update apt package index
      apt:
        update_cache: yes

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker if not installed
      apt:
        name: docker.io
        state: present
      when: docker_installed is failed

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
    
    - debug:
        msg: 
          - "Docker version: {{ docker_version.stdout }}"

- hosts: prod
  become: yes
  tasks:
     - name: Update apt package index
      apt:
        update_cache: yes

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker if not installed
      apt:
        name: docker.io
        state: present
      when: docker_installed is failed

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
    
    - debug:
        msg: 
          - "Docker version: {{ docker_version.stdout }}"
