name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Deploy to Dev EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_IP_ADDRESS}}
          username: ubuntu  # Change if needed
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if ! command -v git &> /dev/null; then
              echo "Git not found, installing..."
              sudo apt-get update
              sudo apt-get install -y git
            else
              echo "Git is already installed."
            fi
          
            # Navigate to the app directory or clone the repository if it doesn't exist
            if [ ! -d "/home/ubuntu/my-python-app" ]; then
              git clone https://github.com/Sowparnika-Poojary/Python_Web_App.git /home/ubuntu/my-python-app
            fi
            
            cd /home/ubuntu/my-python-app
            
            # Pull latest changes
            git pull

            if ! command -v ansible &> /dev/null; then
              echo "Ansible not found, installing..."
              sudo apt-get update
              sudo apt-get install -y ansible
            else
              echo "Ansible is already installed."
            fi

            ansible-playbook -i ansible/hosts, ansible/configuration.yml

            # Remove old images with the same name and no tags
            docker images --filter "reference=${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app" --filter "dangling=true" -q | xargs -r docker rmi
            
            # Build Docker image
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest .

            # Log in to Docker Hub
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            
            # Push the Docker image to Docker Hub
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest

            # Check if the container exists and remove it if it does
            if [ $(docker ps -a -q -f name=my-python-app-container) ]; then
              docker stop my-python-app-container
              docker rm my-python-app-container
            fi

            # Run the Docker container
            docker run -d -p 90:5000 --name my-python-app-container ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest

      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_IP_ADDRESS}}
          username: ubuntu  # Change if needed
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if ! command -v git &> /dev/null; then
              echo "Git not found, installing..."
              sudo apt-get update
              sudo apt-get install -y git
            else
              echo "Git is already installed."
            fi
          
            # Navigate to the app directory or clone the repository if it doesn't exist
            if [ ! -d "/home/ubuntu/my-python-app" ]; then
              git clone https://github.com/Sowparnika-Poojary/Python_Web_App.git /home/ubuntu/my-python-app
            fi
            
            cd /home/ubuntu/my-python-app
            
            # Pull latest changes
            git pull

            if ! command -v ansible &> /dev/null; then
              echo "Ansible not found, installing..."
              sudo apt-get update
              sudo apt-get install -y ansible
            else
              echo "Ansible is already installed."
            fi

            ansible-playbook -i ansible/hosts, ansible/configuration.yml

            # Pull the latest Docker image on QA server
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest

            # Check if the container exists and remove it if it does
            if [ $(sudo docker ps -a -q -f name=my-python-app-container-prod) ]; then
              sudo docker stop my-python-app-container-prod
              sudo docker rm my-python-app-container-prod
            fi

            # Run the Docker container on QA server
            sudo docker run -d -p 90:5000 --name my-python-app-container-prod ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest
