name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Deploy to Dev EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_IP_ADDRESS}}
          username: ubuntu  # Change if needed
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
             # Add the host key to known_hosts
             mkdir -p ~/.ssh
             echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
             chmod 600 ~/.ssh/id_ed25519
             ssh-keyscan -H ${{ secrets.DEV_IP_ADDRESS }} >> ~/.ssh/known_hosts
          
             if ! command -v git &> /dev/null; then
              echo "Git not found, installing..."
              sudo apt-get update
              sudo apt-get install -y git
             else
              echo "Git is already installed."
             fi
             # Navigate to the app directory or clone the repository if it doesn't exist
             if [ ! -d "/home/ubuntu/python-app" ]; then
              git clone https://github.com/Sowparnika-Poojary/Web_App.git /home/ubuntu/python-app
             fi
            
             cd /home/ubuntu/python-app
            
             # Pull latest changes
             git pull

             if ! command -v ansible &> /dev/null; then
              echo "Ansible not found, installing..."
              sudo apt-get update
              sudo apt-get install -y ansible
             else
              echo "Ansible is already installed."
             fi

             # Install Docker module if not installed
             if ! ansible-galaxy collection list | grep community.docker; then
              echo "Installing community.docker collection..."
              ansible-galaxy collection install community.docker
             fi

             ansible-playbook -i /home/ubuntu/python-app/ansible/hosts.ini /home/ubuntu/python-app/ansible/configuration_dev.yml 

      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_IP_ADDRESS}}
          username: ubuntu  # Change if needed
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Add the host key to known_hosts
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan -H ${{ secrets.PROD_IP_ADDRESS }} >> ~/.ssh/known_hosts
            
            if ! command -v git &> /dev/null; then
              echo "Git not found, installing..."
              sudo apt-get update
              sudo apt-get install -y git
            else
              echo "Git is already installed."
            fi
          
            # Navigate to the app directory or clone the repository if it doesn't exist
            if [ ! -d "/home/ubuntu/python-app" ]; then
              git clone https://github.com/Sowparnika-Poojary/Web_App.git /home/ubuntu/python-app
            fi
  
            cd /home/ubuntu/python-app
            
            # Pull latest changes
            git pull

            if ! command -v ansible &> /dev/null; then
              echo "Ansible not found, installing..."
              sudo apt-get update
              sudo apt-get install -y ansible
            else
              echo "Ansible is already installed."
            fi

            ansible-playbook -i /home/ubuntu/python-app/ansible/hosts.ini /home/ubuntu/python-app/ansible/configuration_prod.yml
